# deployment/kubernetes/overlays/prod/poddisruptionbudget.yaml

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: s3-sentinel-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: s3-sentinel-connector