# config/logging.yaml

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s [%(levelname)s] %(name)s:%(lineno)d - %(message)s - %(pathname)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(levelname)s %(name)s %(message)s %(pathname)s %(lineno)d'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/s3_sentinel.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  security:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/security.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

  audit:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/audit.log
    maxBytes: 20971520  # 20MB
    backupCount: 20
    encoding: utf8

loggers:
  s3_sentinel:
    level: INFO
    handlers: [console, file]
    propagate: false

  s3_sentinel.security:
    level: INFO
    handlers: [security]
    propagate: false

  s3_sentinel.audit:
    level: INFO
    handlers: [audit]
    propagate: false

  azure:
    level: WARNING
    handlers: [file]
    propagate: false

root:
  level: INFO
  handlers: [console]